<../master.mk

NUKE = $NUKE *.ca *.ps *.html *.toc


#xfm.toc::	xfm.xfm
#	export XDOC_PASS1=1
#	pfm xfm.xfm /dev/null

xfm_src = cd.im cmds.im cmdtab.im cover_art.im doc_start.im gv_tab.im headtab.im ifroom.im \
	index_snatch.im ixcmds.im lists.im macros.im quickr.im table.im tcfig.im xfm_cover.im

# this requires xfig tools
%.eps : %.fig
	fig2dev -L eps ${prereq} ${target}

imbed_src = cd.im cmds.im cmdtab.im cover_art.im gv_tab.im headtab.im \
	index_snatch.im ixcmds.im lists.im macros.im quickr.im table.im \
	tcfig.im xfm_cover.im logo.eps

xfm.ps: xfm.xfm $xfm_src
	XDOC_PASS1=1 pfm xfm.xfm /dev/null 2>&1
	pfm xfm.xfm xfm.ps

# build the doc fomatted as a single column
xfm_oc.ps:  xfm.xfm $xfm_src
	XDOC_TWOCOL=0 XDOC_PASS1=1 pfm xfm.xfm /dev/null 2>&1
	XDOC_TWOCOL=0 pfm xfm.xfm xfm.ps

xfm_trick.ps:: xfm_trick.xfm
