
# All source and documentation in the xfm tree are published with the following open source license:
# Contributions to this source repository are assumed published with the same license.
#
# =================================================================================================
#    (c) Copyright 1995-2015 By E. Scott Daniels. All rights reserved.
#
#    Redistribution and use in source and binary forms, with or without modification, are
#    permitted provided that the following conditions are met:
#
#        1. Redistributions of source code must retain the above copyright notice, this list of
#            conditions and the following disclaimer.
#
#        2. Redistributions in binary form must reproduce the above copyright notice, this list
#            of conditions and the following disclaimer in the documentation and/or other materials
#            provided with the distribution.
#
#    THIS SOFTWARE IS PROVIDED BY E. Scott Daniels ``AS IS'' AND ANY EXPRESS OR IMPLIED
#    WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
#    FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL E. Scott Daniels OR
#    CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#    CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
#    SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
#    ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
#    NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#    ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#    The views and conclusions contained in the software and documentation are those of the
#    authors and should not be interpreted as representing official policies, either expressed
#    or implied, of E. Scott Daniels.
# =================================================================================================

# Mnemonic:	mkfile
# Abstract: Input file to plan-9 mk (superior to make).
#
#			We'll use the templates directory from the source, not what the user might have
#			installed, to build our doc here.

MK_SHELL = ksh

CLEAN = *.ca *.bcnfile *.ecnfile *.html *.toc *.sp *.eps
NUKE = *.html *.txt *.ps *.pdf $CLEAN

MD_OUT = markdown.md
TXT_OUT = float_mar.txt two_col.txt mix_col.txt markdown.txt
PS_OUT = float_mar.ps two_col.ps mix_col.ps font.ps markdown.ps two_pass.ps
HTML_OUT =
#html_style.html
EPS_SRC = test_2x3.eps

ALL = $EPS_SRC $HTML_OUT $PS_OUT $TXT_OUT $MD_OUT

# this requires xfig tools
%.eps : %.fig
	fig2dev -L eps ${prereq} ${target}

%.ps:: %.xfm ../templates/markdown.im
	pfm -v ${prereq%% *} $target

%.txt:: %.xfm ../templates/markdown.im
	tfm ${prereq%% *} $target
	rm -f *.ecnfile
	rm -f *.bcnfile

%.html:: %.xfm ../templates/markdown.im
	hfm ${prereq%% *} $target
	rm -f *.ecnfile
	rm -f *.bcnfile

%.md:: %.xfm ../templates/markdown.im
	##MARKDOWN=1 tfm ${prereq%% *} stdout | sed 's/^ //' >$target
	MARKDOWN=1 tfm ${prereq%% *} stdout | ../src/scripts/txt2md >$target
	rm -f *.ecnfile
	rm -f *.bcnfile

all:V: $ALL

float_mar.ps::  float_mar.xfm test_2x3.eps
	pfm float_mar.xfm float_mar.ps

mix_col.ps::	mix_col.xfm two_col.xfm

two_pass.ps::	two_pass.xfm
	XFM_PASS=1 pfm two_pass.xfm /dev/null
	XFM_PASS=2 pfm two_pass.xfm two_pass.ps

nuke::
	rm -f $NUKE

clean::
	rm -f $CLEAN
