
To build everything, just run mk in this directory. If
you wish to rebuild everything, not just out of date things
then run:
	MK_PARMS="nuke" mk; mk

Running `mk install` will install the three binaries into
$HOME/bin if that directory exists. 

