AFIwrite( ofile, " /box { 3 index 3 index moveto 3 index 1 index lineto  1 index 1 index lineto 1 index 3 index lineto  closepath stroke pop pop pop pop } def\n" );
AFIwrite( ofile, " /rightxy { dup stringwidth pop 3 index exch sub 2 index moveto show pop pop } def /showstack {  np 0 eq    { show }  {   0 1 np 1 sub\n" );
AFIwrite( ofile, "  { pop  aload pop  dup -1 eq   { pop }  { setrgbcolor }  ifelse  /fs exch def  /ya exch def  exch  findfont fs scalefont setfont\n" );
AFIwrite( ofile, "  ya 0 ne { 0 ya rmoveto } if  show  ya 0 ne { 0 ya -1 mul rmoveto } if  } for  } ifelse  } def /just {  /bc exch def  /wid exch def\n" );
AFIwrite( ofile, "  /np exch def  np 0 eq  { dup /sw exch stringwidth pop def }  { /sw 0 def  0 1 np 1 sub {  /i exch def  i 5 mul 1 add index /fs exch def\n" );
AFIwrite( ofile, "  i 5 mul 4 add index findfont fs scalefont setfont  i 5 mul 3 add index stringwidth pop  /sw exch sw add def  } for  } ifelse  wid sw sub bc div\n" );
AFIwrite( ofile, "  /bs exch def  np 0 eq  { bs 0 32 4 index widthshow pop }  { 0 1 np 1 sub {  pop  aload pop  dup -1 eq   { pop }  { setrgbcolor }\n" );
AFIwrite( ofile, "  ifelse  /fs exch def  /ya exch def  exch findfont fs scalefont setfont  ya 0 ne { 0 ya rmoveto } if  bs 0 32 3 index widthshow pop\n" );
AFIwrite( ofile, "  ya 0 ne { 0 ya -1 mul rmoveto } if  } for  } ifelse } def /cent {   /np exch def   /wid exch def   np 0 eq    { dup /sw exch stringwidth pop def }\n" );
AFIwrite( ofile, "   { /sw 0 def  0 1 np 1 sub {   /i exch def   i 5 mul 1 add index /fs exch def  i 5 mul 4 add index findfont fs scalefont setfont \n" );
AFIwrite( ofile, "  i 5 mul 3 add index stringwidth pop  /sw exch sw add def   } for    } ifelse  wid sw sub 2 div 0 rmoveto showstack  } def /right { \n" );
AFIwrite( ofile, "  /np exch def   /wid exch def   /sw 0 def   0 1 np 1 sub {   /i exch def    i 5 mul 1 add /fs exch def   i 5 mul 4 add index findfont fs scalefont setfont\n" );
AFIwrite( ofile, "   i 5 mul 3 add index stringwidth pop    /sw exch sw add def   } for   currentpoint exch wid add sw sub exch moveto showstack  } def\n" );
AFIwrite( ofile, " /splat { /np exch def showstack } def xlate\n" );
